[package]
name = "nibi-dev"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
# See more Cargo.toml key definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0.188", features = ["derive"]}
serde_json = { version = "1.0.107" }
home = "0.5"
thiserror = "1"
anyhow = { version = "1", features = ["backtrace"]}
reqwest = { version = "0.11", features = ["blocking"] }

[dev-dependencies]
assert_cmd = "2"

[[bin]]
name = "get-nibid"
path = "bin/get_nibid.rs"