[package]
name = "bash-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
# See more Cargo.toml key definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.188", features = ["derive"]}
serde_json = { version = "1.0.107" }
thiserror = "1"
anyhow = { version = "1", features = ["backtrace"]}

[dev-dependencies]
assert_cmd = "2"